package com.inventory.app.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity; 
import jakarta.persistence.GeneratedValue; 
import jakarta.persistence.GenerationType; 
import jakarta.persistence.Id; 
import lombok.AllArgsConstructor; 
import lombok.Data; 
import lombok.NoArgsConstructor; 

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class UserInfo { 

	// The id will serve as the primary identifier and it will be autogenerated
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	private int id; 

	// making the name colum unique so that each user name is unique
    @Column(unique = true)
	private String name; 

	private String password; 

	// Constructor generation has already been covered by @AllArgsConstructor annotations above

} 
